export const SEAWEEDFS_MODULE_OPTIONS = Symbol('SEAWEEDFS_MODULE_OPTIONS');
export const SEAWEEDFS_FILER_CLIENT = Symbol('SEAWEEDFS_FILER_CLIENT');
export const SEAWEEDFS_S3_CLIENT = Symbol('SEAWEEDFS_S3_CLIENT');
export const SEAWEEDFS_FILER_SERVICE = Symbol('SEAWEEDFS_FILER_SERVICE');
export const SEAWEEDFS_S3_SERVICE = Symbol('SEAWEEDFS_S3_SERVICE');
export const SEAWEEDFS_SERVICE = Symbol('SEAWEEDFS_SERVICE');

export const DEFAULT_S3_REGION = 'us-east-1';
export const DEFAULT_FILER_TIMEOUT = 30000;
export const DEFAULT_FILER_RETRIES = 3;
export const DEFAULT_S3_PRESIGN_EXPIRES = 3600;
